/* generated by Buddy 3.1.0 */

require.register('src/lib/primitives/precipitation.js', function(require, module, exports) {
    'use strict';
    
    var utils = require('src/lib/utils.js');
    
    /**
     * Render precipitation svg primitive
     * @param {Object} options
     * @returns {String}
     */
    module.exports = function render(options) {
      return utils.getUseElementString('#' + options.primitive, options);
    };
});
require.register('src/lib/primitives/lightning.js', function(require, module, exports) {
    'use strict';
    
    var utils = require('src/lib/utils.js');
    
    /**
     * Render lightning svg primitive
     * @param {Object} options
     * @returns {String}
     */
    module.exports = function render(options) {
      return utils.getUseElementString('#lightning', options);
    };
});
require.register('src/lib/primitives/fog.js', function(require, module, exports) {
    'use strict';
    
    var utils = require('src/lib/utils.js');
    
    /**
     * Render fog svg primitive
     * @param {Object} options
     * @returns {String}
     */
    module.exports = function render(options) {
      return utils.getUseElementString('#fog', options);
    };
});
require.register('src/lib/primitives/cloud.js', function(require, module, exports) {
    'use strict';
    
    var utils = require('src/lib/utils.js');
    
    /**
     * Render cloud svg primitive
     * @param {Object} options
     * @returns {String}
     */
    module.exports = function render(options) {
      return utils.getUseElementString('#cloud', options);
    };
});
require.register('src/lib/utils.js', function(require, module, exports) {
    'use strict';
    
    var MAX_WIDTH = 100;
    
    module.exports = {
      /**
       * Parse 'options'
       * @param {Object} options
       * @returns {Object}
       */
    
      parse: function parse(options) {
        var opts = {};
    
        opts.visible = true;
        // opts.scale = (type == 'canvas') ? capabilities.backingRatio : 1;
        opts.scaleX = 1;
        opts.scaleY = 1;
        opts.primitive = options.primitive;
        opts.x = Math.round(options.x * opts.scaleX);
        opts.y = Math.round(options.y * opts.scaleY);
        opts.scaleX = (options.scaleX || 1) * opts.scaleX;
        opts.scaleY = (options.scaleY || 1) * opts.scaleY;
        opts.flip = options.flip;
        opts.tint = options.tint || 1;
        opts.winter = options.winter;
        opts.variation = options.variation != null ? '' + options.variation : '';
        opts.class = opts.primitive + opts.variation + '-primitive';
    
        return opts;
      },
    
      /**
       * Retrieve stringified attribute object for <use>
       * @param {String} link
       * @param {Object} options
       * @returns {String}
       */
      getUseElementString: function getUseElementString(link, options) {
        var props = {
          class: options.class,
          'xlink:href': link,
          x: '0',
          y: '0',
          width: '100',
          height: '100',
          transform: options.flip ? 'translate(' + (MAX_WIDTH * options.scaleX + options.x) + ',' + options.scaleY * options.y + ') scale(' + -1 * options.scaleX + ', ' + options.scaleY + ')' : 'translate(' + options.x + ',' + options.y + ') scale(' + options.scaleX + ', ' + options.scaleY + ')'
        };
    
        var str = '<use';
    
        for (var prop in props) {
          str += ' ' + prop + '="' + props[prop] + '"';
        }
        str += '></use>';
    
        return str;
      }
    };
});
require.register('src/lib/primitives/celestial.js', function(require, module, exports) {
    'use strict';
    
    var utils = require('src/lib/utils.js');
    
    /**
     * Render sun, winter sun, or moon svg primitive
     * @param {Object} options
     * @returns {String}
     */
    module.exports = function render(options) {
      return utils.getUseElementString(options.primitive == 'moon' ? '#moon' : options.winter ? '#sunWinter' : '#sun', options);
    };
});
require.register('src/lib/primitives/index.js', function(require, module, exports) {
    'use strict';
    
    var celestial = require('src/lib/primitives/celestial.js'),
        cloud = require('src/lib/primitives/cloud.js'),
        fog = require('src/lib/primitives/fog.js'),
        lightning = require('src/lib/primitives/lightning.js'),
        precipitation = require('src/lib/primitives/precipitation.js');
    
    module.exports = {
      cloud: cloud,
      fog: fog,
      lightning: lightning,
      moon: celestial,
      raindrop: precipitation,
      snowflake: precipitation,
      sun: celestial
    };
});
require.register('src/index.js', function(require, module, exports) {
    'use strict'
    
    /**
     * Weather symbol component.
     */
    
    ;
    var graphicsComponent = require('@yr/graphics-component'),
        primitives = require('src/lib/primitives/index.js'),
        recipes = require('src/lib/recipes.js'),
        utils = require('src/lib/utils.js');
    
    module.exports = {
      /**
       * Instance factory
       * @param {Object} options
       * @returns {Function}
       */
    
      create: function create(options) {
        options.renderInnerSvg = renderInnerSvg;
    
        return graphicsComponent.create(options);
      }
    };
    
    /**
     * Render inner svg string for 'id'
     * @param {String} id
     * @returns {String}
     */
    function renderInnerSvg(id) {
      var recipe = recipes[id];
    
      if (!recipe) return '';
    
      return recipe.reduce(function (html, r) {
        var opts = utils.parse(r);
    
        return html += primitives[opts.primitive](opts);
      }, '');
    }
});
require.register('src/lib/recipes.js', function(require, module, exports) {
    'use strict';
    
    var base = {
      sun1: [{
        primitive: 'sun',
        x: 5,
        y: 0
      }],
      sun2: [{
        primitive: 'sun',
        x: 0,
        y: 0
      }],
      sun3: [{
        primitive: 'sun',
        x: 0,
        y: 0,
        scaleX: 0.666666667,
        scaleY: 0.666666667
      }],
      sunWinter1: [{
        primitive: 'sun',
        x: 5,
        y: 37,
        winter: true
      }],
      sunWinter2: [{
        primitive: 'sun',
        x: 0,
        y: 37,
        winter: true
      }],
      sunWinter3: [{
        primitive: 'sun',
        x: 0,
        y: 23,
        scaleX: 0.666666667,
        scaleY: 0.666666667,
        winter: true
      }],
      moon1: [{
        primitive: 'moon',
        x: 15,
        y: 5
      }],
      moon2: [{
        primitive: 'moon',
        x: 5,
        y: 5
      }],
      moon3: [{
        primitive: 'moon',
        x: 0,
        y: 3,
        scaleX: 0.714285714,
        scaleY: 0.714285714
      }],
      '02': [{
        primitive: 'cloud',
        x: 35,
        y: 40,
        scaleX: 0.714285714,
        scaleY: 0.714285714,
        variation: 1
      }],
      '03': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 1
      }],
      40: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'raindrop',
        x: 32,
        y: 87
      }, {
        primitive: 'raindrop',
        x: 56,
        y: 78
      }],
      '05': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'raindrop',
        x: 32,
        y: 78
      }, {
        primitive: 'raindrop',
        x: 45,
        y: 87
      }, {
        primitive: 'raindrop',
        x: 60,
        y: 78
      }],
      41: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'raindrop',
        x: 18,
        y: 78
      }, {
        primitive: 'raindrop',
        x: 32,
        y: 87
      }, {
        primitive: 'raindrop',
        x: 47,
        y: 79
      }, {
        primitive: 'raindrop',
        x: 60,
        y: 78
      }, {
        primitive: 'raindrop',
        x: 74,
        y: 87
      }],
      42: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'snowflake',
        x: 29,
        y: 88
      }, {
        primitive: 'raindrop',
        x: 60,
        y: 79
      }],
      '07': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'snowflake',
        x: 30,
        y: 79
      }, {
        primitive: 'raindrop',
        x: 46,
        y: 86
      }, {
        primitive: 'raindrop',
        x: 60,
        y: 80
      }],
      43: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'snowflake',
        x: 15,
        y: 79
      }, {
        primitive: 'raindrop',
        x: 32,
        y: 86
      }, {
        primitive: 'raindrop',
        x: 47,
        y: 80
      }, {
        primitive: 'snowflake',
        x: 58,
        y: 88
      }, {
        primitive: 'raindrop',
        x: 74,
        y: 80
      }],
      44: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'snowflake',
        x: 29,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 58,
        y: 79
      }],
      '08': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'snowflake',
        x: 30,
        y: 79
      }, {
        primitive: 'snowflake',
        x: 44,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 58,
        y: 79
      }],
      45: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'snowflake',
        x: 15,
        y: 79
      }, {
        primitive: 'snowflake',
        x: 29,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 44,
        y: 79
      }, {
        primitive: 'snowflake',
        x: 58,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 72,
        y: 79
      }],
      24: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'raindrop',
        x: 28,
        y: 87
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 58,
        y: 78
      }],
      '06': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'raindrop',
        x: 29,
        y: 78
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 50,
        y: 87
      }, {
        primitive: 'raindrop',
        x: 65,
        y: 78
      }],
      25: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'raindrop',
        x: 18,
        y: 78
      }, {
        primitive: 'raindrop',
        x: 29,
        y: 87
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 55,
        y: 79
      }, {
        primitive: 'raindrop',
        x: 68,
        y: 78
      }, {
        primitive: 'raindrop',
        x: 82,
        y: 87
      }],
      26: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'snowflake',
        x: 26,
        y: 88
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 58,
        y: 79
      }],
      20: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'snowflake',
        x: 27,
        y: 79
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 50,
        y: 86
      }, {
        primitive: 'raindrop',
        x: 64,
        y: 80
      }],
      27: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'snowflake',
        x: 15,
        y: 79
      }, {
        primitive: 'raindrop',
        x: 30,
        y: 86
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'raindrop',
        x: 55,
        y: 80
      }, {
        primitive: 'snowflake',
        x: 66,
        y: 88
      }, {
        primitive: 'raindrop',
        x: 82,
        y: 80
      }],
      28: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 2
      }, {
        primitive: 'snowflake',
        x: 26,
        y: 88
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'snowflake',
        x: 58,
        y: 79
      }],
      21: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 3
      }, {
        primitive: 'snowflake',
        x: 26,
        y: 79
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'snowflake',
        x: 52,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 66,
        y: 79
      }],
      29: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 4
      }, {
        primitive: 'snowflake',
        x: 13,
        y: 79
      }, {
        primitive: 'snowflake',
        x: 27,
        y: 88
      }, {
        primitive: 'lightning',
        x: 42,
        y: 51
      }, {
        primitive: 'snowflake',
        x: 55,
        y: 79
      }, {
        primitive: 'snowflake',
        x: 69,
        y: 88
      }, {
        primitive: 'snowflake',
        x: 83,
        y: 79
      }]
    };
    
    module.exports = {
      '01d': base.sun1,
      '02d': base.sun2.concat(base['02']),
      '03d': base.sun3.concat(base['03']),
      '40d': base.sun3.concat(base['40']),
      '05d': base.sun3.concat(base['05']),
      '41d': base.sun3.concat(base['41']),
      '42d': base.sun3.concat(base['42']),
      '07d': base.sun3.concat(base['07']),
      '43d': base.sun3.concat(base['43']),
      '44d': base.sun3.concat(base['44']),
      '08d': base.sun3.concat(base['08']),
      '45d': base.sun3.concat(base['45']),
      '24d': base.sun3.concat(base['24']),
      '06d': base.sun3.concat(base['06']),
      '25d': base.sun3.concat(base['25']),
      '26d': base.sun3.concat(base['26']),
      '20d': base.sun3.concat(base['20']),
      '27d': base.sun3.concat(base['27']),
      '28d': base.sun3.concat(base['28']),
      '21d': base.sun3.concat(base['21']),
      '29d': base.sun3.concat(base['29']),
    
      '01m': base.sunWinter1,
      '02m': base.sunWinter2.concat(base['02']),
      '03m': base.sunWinter3.concat(base['03']),
      '40m': base.sunWinter3.concat(base['40']),
      '05m': base.sunWinter3.concat(base['05']),
      '41m': base.sunWinter3.concat(base['41']),
      '42m': base.sunWinter3.concat(base['42']),
      '07m': base.sunWinter3.concat(base['07']),
      '43m': base.sunWinter3.concat(base['43']),
      '44m': base.sunWinter3.concat(base['44']),
      '08m': base.sunWinter3.concat(base['08']),
      '45m': base.sunWinter3.concat(base['45']),
      '24m': base.sunWinter3.concat(base['24']),
      '06m': base.sunWinter3.concat(base['06']),
      '25m': base.sunWinter3.concat(base['25']),
      '26m': base.sunWinter3.concat(base['26']),
      '20m': base.sunWinter3.concat(base['20']),
      '27m': base.sunWinter3.concat(base['27']),
      '28m': base.sunWinter3.concat(base['28']),
      '21m': base.sunWinter3.concat(base['21']),
      '29m': base.sunWinter3.concat(base['29']),
    
      '01n': base.moon1,
      '02n': base.moon2.concat(base['02']),
      '03n': base.moon3.concat(base['03']),
      '40n': base.moon3.concat(base['40']),
      '05n': base.moon3.concat(base['05']),
      '41n': base.moon3.concat(base['41']),
      '42n': base.moon3.concat(base['42']),
      '07n': base.moon3.concat(base['07']),
      '43n': base.moon3.concat(base['43']),
      '44n': base.moon3.concat(base['44']),
      '08n': base.moon3.concat(base['08']),
      '45n': base.moon3.concat(base['45']),
      '24n': base.moon3.concat(base['24']),
      '06n': base.moon3.concat(base['06']),
      '25n': base.moon3.concat(base['25']),
      '26n': base.moon3.concat(base['26']),
      '20n': base.moon3.concat(base['20']),
      '27n': base.moon3.concat(base['27']),
      '28n': base.moon3.concat(base['28']),
      '21n': base.moon3.concat(base['21']),
      '29n': base.moon3.concat(base['29']),
    
      15: [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 1
      }, {
        primitive: 'fog',
        x: 0,
        y: 76
      }],
      '04': [{
        primitive: 'cloud',
        x: 5,
        y: 25,
        variation: 1
      }],
      46: base['40'],
      '09': base['05'],
      10: base['41'],
      47: base['42'],
      12: base['07'],
      48: base['43'],
      49: base['44'],
      13: base['08'],
      50: base['45'],
      30: base['24'],
      22: base['06'],
      11: base['25'],
      31: base['26'],
      23: base['20'],
      32: base['27'],
      33: base['28'],
      14: base['21'],
      34: base['29']
    };
});
require.register('react-dom/index.js#0.14.3', function(require, module, exports) {
    'use strict';
    
    module.exports = require('react/lib/ReactDOM');
    
});
require.register('src/preview.js', function(require, module, exports) {
    'use strict';
    
    var grid = require('@yr/graphics-component/src/previewGrid'),
        ReactDOM = require('react-dom/index.js#0.14.3'),
        recipes = require('src/lib/recipes.js'),
        symbolComponent = require('src/index.js'),
        el = document.getElementById('viewport'),
        symbol = symbolComponent.create({ rootImagePath: 'dist/png' });
    
    ReactDOM.render(grid({
      ids: object.keys(recipes),
      graphic: symbol
    }), el);
});
require('src/preview.js');